# ==============================================================================
# Configuration
# ==============================================================================
title: "A great title!"
theme: "chisel"

# ==============================================================================
# Locales
# ==============================================================================
defaultContentLanguage: "en"
defaultContentLanguageInSubDir: true
enableMissingTranslationPlaceholders: true
hasCJKLanguage: false
removePathAccents: true

# ==============================================================================
# Hugo Built-in Features
# ==============================================================================
disableKinds:
enableInlineShortcodes: true