# ----------------------------- custom parameters ---------------------------- #
disableThemeSwitcher: true

title: "Liuteria d'Autore"
author: "Andrea Spada"
description: "Maker and Restorer of Fine String Instruments"
profilePicture: "images/profile.png"

socialIcons:
  - icon: fab fa-github
    title: GitHub
    url: 'https://github.com/liuteriadautore'
  - icon: fab fa-instagram
    title: instagram
    url: 'https://www.instagram.com/andrea.spada.liutaio'
  - icon: fas fa-envelope
    title: e-mail
    url: 'mailto:liuteriadautore@gmail.com'
