# ----------------------------- custom parameters ---------------------------- #
disableThemeSwitcher: true

title: "Liuteria d'Autore"
author: "Andrea Spada"
description: "Maker and Restorer of Fine String Instruments"
profilePicture: "images/profile.png"

social:
  facebook: 'https://www.facebook.com/user_or_page'
  github: 'https://github.com/user'
  instagram: 'https://instagram.com/user'
  linkedin: 'https://www.linkedin.com/in/user'
  pinterest: 'https://www.pinterest.com/user'
  stackoverflow: 'https://stackoverflow.com/users/user'
  twitter: 'https://twitter.com/axiomtheme'
  youtube: 'https://www.youtube.com/user'
  footer:
    - twitter
    - github
    - instagram

logo:
  inline: true
  path: "logoAS.svg"