# ---------------------------------- render ---------------------------------- #
canonifyURLs: true
uglyurls: false
disableAliases: false
disableHugoGeneratorInject: false
disableKinds: []
disableLiveReload: false
enableEmoji: true
enableGitInfo: false
ignoreCache: true
ignoreFiles: []
metaDataFormat: "yaml"
verbose: true
watch: true

# ----------------------------------- build ---------------------------------- #
cleanDestinationDir: true
buildDrafts: false
buildFuture: false
buildExpired: false

# ---------------------------------------------------------------------------- #
#                                  Source Tree                                 #
# ---------------------------------------------------------------------------- #

# ------------------------ maitenance and development ------------------------ #
archetypeDir: "src/config/_types"

# --------------------------------- includes --------------------------------- #
assetDir: "src/include/assets"
themesDir: "src/include/themes"

# ------------ all site related content folders lives under 'site' ------------ #
i18nDir: "src/site/locales"
contentDir: "src/site/content"
dataDir: "src/site/data"
layoutDir: "src/site/layouts"
staticDir: "src/site/static"


# ---------------------------------- output ---------------------------------- #
publishDir: "build"
resourceDir: "resources"
