# ==============================================================================
# PUBLISH OVERRIDES
# ==============================================================================
baseURL: https://yourwebsiteURL
googleAnalytics: ""

enableGitInfo: true
verbose: false
buildDrafts: false
buildFuture: false
publishDir: "dist/public"